name: Bug report
about: Report a bug
labels: bug

body:
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How do we reproduce the issue?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: input
    attributes:
      label: Browser
      description: Browser name and version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Logs, screenshots, or extra info
    validations:
      required: false
